### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by CHNxindong** [Ground-A-Video/Ground-A-Video#1]
Great work. Expecting the code release early!

**Comment by Ground-A-Video** [comment]
@CHNxindong 
Thank you for your comment and interest! We plan to release the initial code within three weeks and later will release user-friendly demo.

**Comment by CHNxindong** [comment]
Thanks for your quick reply!

**Comment by ninjasaid2k** [comment]
> @CHNxindong Thank you for your comment and interest! We plan to release the initial code within three weeks and later will release user-friendly demo.
